# Fly.io configuration for ThriftTech Email Backend
app = "thrifttech-email-backend"
primary_region = "iad"

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "node server.js"
